events { worker_connections 1024; }

http {
    # Định nghĩa một cụm máy chủ tên là 'my_web_servers'
    upstream my_web_servers {
        server web1:3000;
        server web2:3000;
        server web3:3000;
    }

    server {
        # Nginx (Lễ tân) đứng ở cửa số 80 để đón khách
        listen 80;
        
        location / {
            # Bất kỳ ai vào cũng sẽ được đẩy vào cụm 'my_web_servers' bên trên
            proxy_pass http://my_web_servers;
        }
    }
}